# Generated by Django 3.2.2 on 2024-01-06 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('salespeople', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('color', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('mileage', models.IntegerField(blank=True, null=True)),
                ('sold', models.BooleanField(default=False)),
                ('date_sold', models.DateField(blank=True, null=True)),
                ('vin', models.CharField(blank=True, max_length=17, unique=True)),
                ('car_type', models.CharField(choices=[('Convertible', 'Convertible'), ('Coupe', 'Coupe'), ('Sedan', 'Sedan'), ('SUV', 'SUV'), ('Truck', 'Truck'), ('Wagon', 'Wagon')], default='Sedan', max_length=15)),
                ('salesperson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sold_cars', to='salespeople.salespeople')),
            ],
        ),
    ]
