# Generated by Django 3.2.2 on 2024-07-13 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20240713_0328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_color',
            field=models.CharField(choices=[('Black', 'Black'), ('Blue', 'Blue'), ('Brown', 'Brown'), ('Gold', 'Gold'), ('Green', 'Green'), ('Grey', 'Grey'), ('Orange', 'Orange'), ('Red', 'Red'), ('Silver', 'Silver'), ('White', 'White')], default='Black', max_length=15),
        ),
    ]
